### ISSUE TITLE
can not do action manual capture via extension

### ISSUE THREAD

**Issue by lambaodiep** [commercetools/commercetools-adyen-integration#1018]
I am using CT API Playground to add a capture transaction, but the error happen in that process, I have already attached the error here, Could you please help me to check again why this error happen, how can I solve it?
I am using v10.0.0

This is my payload I call CT API playground

`{
 "version": 17,
  "actions": [{
    "action": "addTransaction",
    "transaction": {
      "type": "Charge",
      "amount": {
        "currencyCode": "EUR",
        "centAmount": 11293
      },
      "captureDelayHours": 1,
      "state": "Initial"
    }
  }]
}`

This is the log for request and response when code call method **callAdyen**
`2022-09-20T04:17:17.690Z	56363d18-07a2-4fc8-81c2-1931b76aacc2	INFO	request + response {
  body: '{"modificationAmount":{"value":11293,"currency":"EUR"},"originalReference":"JHCS4GQLNLBX8N82","metadata":{"ctProjectKey":"spabc0-poc"},"merchantAccount":"Spabc0_de"}'
} {
  name: 'SyntaxError',
  message: 'Unexpected token M in JSON at position 4',
  stack: 'SyntaxError: Unexpected token M in JSON at position 4\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at Response.json (file:///var/task/node_modules/node-fetch/src/body.js:149:15)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
    '    at async fetchAsync (file:///var/task/src/service/web-component-service.js:220:24)\n' +
    '    at async callAdyen (file:///var/task/src/service/web-component-service.js:184:35)\n' +
    '    at async Object.execute (file:///var/task/src/paymentHandler/manual-capture.handler.js:31:33)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Object.handlePayment (file:///var/task/src/paymentHandler/payment-handler.js:53:28)\n' +
    '    at async Runtime.handler (file:///var/task/index.js:22:27)'
}`

**Comment by lojzatran** [comment]
Hi @lambaodiep,

Thanks for contacting us.

I checked your API call and it is working fine for me.

This error usually happens when the returned response cannot be parsed to JSON (probably it is not a valid JSON). We would need payment-specific details related to your project to investigate. Therefore please create an issue in the [support portal](https://jira.commercetools.com/servicedesk/customer/portal/1).

**Comment by lambaodiep** [comment]
hi @lojzatran 

Thanks for you response, In my case I checked in Adyen, the status of the transaction does not update. It seems error , and Your link I can't not access anymore,

**Comment by lojzatran** [comment]
Yes, it could be as you said, but without more detailed information it's hard to investigate further. Does this link work for you? You have to create an account there and then create the support ticket. There we can help you further as this issue seems to be related to your commercetools project. https://jira.commercetools.com/servicedesk/customer/portal/1

**Comment by lambaodiep** [comment]
hi @lojzatran 

Thanks for update, at the time I wrote my comment, it is extremely slow and the web page can not render, now I can access, I am creating a ticket.

**Comment by butenkor** [comment]
@lambaodiep Did you create a support ticket? Can this ticket be closed?

**Comment by MartinAKQA** [comment]
I am struggling with the exact same issue right now, @lambaodiep do you remember what the resolve for this was?
