### ISSUE TITLE
removeSensitiveData property

### ISSUE THREAD

**Issue by b-michalski-expondo** [commercetools/commercetools-adyen-integration#1074]
Hi,
I'm trying to set removeSensitiveData property to false in makePaymentRequest as it says in docs. but Adyen is returning this
![image](https://user-images.githubusercontent.com/125367988/218738424-7ab7ea4e-5add-4d00-95a7-9b4f4deb8f52.png)
It's working fine when I set it in integration's config. Am I doing something wrong?

**Comment by leungkinghin** [comment]
Hello @b-michalski-expondo 
We have tried out in our own e2e test with `removeSensitiveData` in `makePaymentRequest`, it should return properly the response. Actually this attribute is removed before the integration sends a fetch request to Adyen API.

May we know which version of this integration you are using ?

Also, if you feel convenient, can you send us the `makePaymentRequest` payload so that we can try to reproduce the case on our side.

**Comment by b-michalski-expondo** [comment]
Sorry for trouble, your comment made me realize that we might not use the newest version of integration. We're using 9.10 so the feature I was expecting is just not there yet. We'll update adyen integration and this should solve the problem. Thank you

**Comment by leungkinghin** [comment]
@b-michalski-expondo No worry. Good to know the problem has been resolved.
