### ISSUE TITLE
Refund part of captured amount

### ISSUE THREAD

**Issue by christianandersson** [commercetools/commercetools-adyen-integration#399]
Perhaps this will not be an issue when the next major is released.. However, we've been using a build of the Web-components branch for some time. How would you go about refunding a partial amount? The cancellation action calls the cancelOrRefund endpoint at Adyen here:
 
https://github.com/commercetools/commercetools-adyen-integration/blob/support-adyen-web-components/extension/src/service/web-component-service.js#L24

This API call will cancel everything that has been captured and not just the amount set on the transaction. See docs:

https://docs.adyen.com/checkout/cancel-or-refund#cancel-or-refund-a-payment

I think you'd have to call the refund endpoint at Adyen to refund part of the payment.

https://docs.adyen.com/checkout/refund

**Comment by butenkor** [comment]
Hi @christianandersson, unfortunately In our first MVP we did not consider supporting partial charges or refunds. We might add it though soon (regarding timing please create support ticket here http://support.commercetools.com). If you are in a rush you can also consider providing a PR, where depending on the refund transaction amount the extension would do a partial refund instead of cancelOrRefund.

**Comment by christianandersson** [comment]
Thanks you @butenkor 
There 's probably no way for a retailer to get around such a limitation, unless they can handle refunds in the Adyen payment portal. We might patch the current version and add support for this, if so, we can submit a PR.
