### ISSUE TITLE
Web Component Integration guide should mention about additional params for 3DS Support

### ISSUE THREAD

**Issue by Fifciu** [commercetools/commercetools-adyen-integration#622]
It should mention I have to add:
```js
additionalData: {
  allow3DS2: true
},
channel: 'web',
origin: 'http://localhost:3000'
```
to the `makePaymentRequest`'s value

https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#step-5-make-a-payment

**Comment by Fifciu** [comment]
Also `returnUrl` field for 3DS in version 1

**Comment by butenkor** [comment]
Thank you for the feedback. In general integration is payment method agnostic and supports all the web-component based methods listed by Adyen: https://docs.adyen.com/online-payments/supported-payment-methods

In order to avoid documentation duplication we did not describe all the possible parameters for every available payment method but rather provided some examples. Additionally, some parameters are generated by the Adyen JS web-component and some has to be provided by the integrator, depending on their requirements. 

If you want to look up all the possible option/parameters then check `Web Components` section of the desired payment method listed in the navigation here:

https://docs.adyen.com/payment-methods

For example 3D-secure related documentation can be found here:
https://docs.adyen.com/online-payments/3d-secure/native-3ds2/web-component

**Comment by Fifciu** [comment]
I understand your point @butenkor , this is exactly what I did. However, I think it is worth at least put this link in the documentation and warn developers about importance of implementing it (3DS Support). They might be unconscious about importance of implementing 3DS and end up without it on production - which would cause big losses in money for the merchant.

**Comment by butenkor** [comment]
Sure, we will improve the documentation. 

> They might be unconscious about importance of implementing 3DS and end up without it on production - which would cause big losses in money for the merchant.

The `allow3DS2` setting above does not switch on/off 3D-Secure as this would be easily manipulated by the users already in the browser. According to the [docs](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/ios-component#make-a-payment):
> Set to true. Indicates that your integration can handle native 3D Secure 2 authentication.

By default 3D-Secure is on and you can mange it in Adyen risk management rules.
https://docs.adyen.com/risk-management/dynamic-3d-secure#default-rules

**Comment by Fifciu** [comment]
Great thanks!

**Comment by ahmetoz** [comment]
The changes are merged to master, hereby I'm closing the issue. Please let me know for additional updates.
