### ISSUE TITLE
Support for PayByLink

### ISSUE THREAD

**Issue by Fifciu** [commercetools/commercetools-adyen-integration#717]
Let's add the support for Pay By Link: https://docs.adyen.com/online-payments/pay-by-link/api

**Comment by lojzatran** [comment]
Hi @Fifciu, thanks for the issue. I will redirect your request further and let you know if we're going to support it or not.

**Comment by Fifciu** [comment]
I am working on it right now and going to prepare a PR when it is ready

**Comment by Fifciu** [comment]
I am working on it. Gonna prepare a PR when it's ready

**Comment by anamilosevic6** [comment]
We are closing this issue as we have decided not to include paybylink in our integration. The use case was to add paybylink instead of using the web-component for checkout. In our experience it is always better to use a web-component (where possible) as it gives much more flexibility and better user experience.
