### ISSUE TITLE
Update Payment status in list of orders

### ISSUE THREAD

**Issue by Fifciu** [commercetools/commercetools-adyen-integration#734]
I think it is very important to update `Payment status` in the list of Orders. Currently, it has an empty value:

![image](https://user-images.githubusercontent.com/30155292/122358903-62b30000-cf55-11eb-8dbd-edb830a68f6b.png)

`Payment status` should contain some value jak `Paid`, `Succeed`, `Failed`, `Rejected` or smth like that.

**Comment by maheshiwtc** [comment]
Hi CT, while testing Adyen with CT, we have encountered this issue.

**Comment by butenkor** [comment]
This is expected since the integration is generic and should not interfere the with customer specific cart or order process and how it deals with the statuses. It means that integration does not modify neither cart, customer nor the order. It is the responsibility of the shop logic to create an order and decide which [orderState](https://docs.commercetools.com/api/projects/orders#orderstate)/[state](https://docs.commercetools.com/api/projects/states#state)/[paymentState](https://docs.commercetools.com/api/projects/orders#paymentstate) it should get. For example on order creation, based on the successful transaction details one can set on the order `paymentState=Paid` and update it asynchronously by subscription to the [PaymentTransactionAddedMessage](https://docs.commercetools.com/api/message-types#paymenttransactionaddedmessage) and [PaymentTransactionStateChangedMessage](https://docs.commercetools.com/api/message-types#paymenttransactionstatechangedmessage) messages. You probably also noticed that integration does not use/occupy payment fields like [PaymentStatus](https://docs.commercetools.com/api/projects/payments#paymentstatus) state which also allows the integration users to define custom states based on their needs.

> When the payment details are flown in to CT, payment status is successful in the individual order details (under payment tab), however grid does not show the same status (or any status).

Yes, you see payment details on the order under payment tab since it shows the status of the payments referenced by the order. In the grid you see only the [paymentState](https://docs.commercetools.com/api/projects/orders#paymentstate) which might be an aggregated value which is set by the store logic since an order can reference multiple payments (i.e.: partial payments) with a different state and integration can not guess which combination of which payments should lead to which order payment state. Same goes with the partial refund process and similar.
