### ISSUE TITLE
HTTP Auth for module deployed as a Google Function

### ISSUE THREAD

**Issue by Fifciu** [commercetools/commercetools-adyen-integration#904]
Hello,
I am working on moving our extension & notification modules from k8s pods to Google Functions. I've easily deployed them there. However, I do not see a simple way to limit the access. I want only CT to be able to send calls to our Trigger URL because if anyone did it, it would generate big costs in GCP.

I've checked Google documentation and I see it might require an additional request for the auth key. I think it is not really a proper way of doing that in the current case. Do you know how we could protect Trigger URL without code modifications?

**Comment by lojzatran** [comment]
Hi @Fifciu

Thank you for your request. Unfortunately in our team we don't have any experience with protecting the Trigger URL. Maybe you can have a look at following links: https://cloud.google.com/load-balancing/docs/negs/internet-neg-concepts#authenticating_requests, https://cloud.google.com/vpc-service-controls/docs/service-perimeters.

I'm closing the ticket as we cannot help you here. Let us know if you have any comments or further questions.

**Comment by Fifciu** [comment]
Trigger URL is protected by default and disabling it could generate huge costs in GCP. 

It looks like I have to send an additional request for the auth token and put it in Commercetools' extension. However, TTL of auth token in GCP is only 1h, so I would need to update it in CT every hour! That sounds ridiculous to me. That's why I am asking you for detailed instructions on deploying it as Google Function. The current one doesn't contain information about handling tokens that are crucial for Serverless functions.

**Comment by ahmetoz** [comment]
Hey @Fifciu,
Thanks for the request;

> I want only CT to be able to send calls to our Trigger URL because if anyone did it, it would generate big costs in GCP. Trigger URL is protected by default and disabling it could generate huge costs in GCP. 

I'm not sure I got the concern related to costs (assuming an attacker who wants to load the functions need to know the trigger url in the commercetools which normally should not because the request/response should be in https so trigger url will be secured) in case with exposing an url to internet. You might check the basic auth mechanism (https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/HowToRun.md#commercetools) for extension and hmac for the notification which secures the integration from insecure calls.

> However, TTL of auth token in GCP is only 1h, so I would need to update it in CT every hour! That sounds ridiculous to me. 

Currently, I could not find a mechanism on google functions that covers your scenario by default or sth like an api key that auth info is always same on the trigger url (as you said this might be another security issue). I guess in this case you might check a proxy server approach and do the authentication before going to google function which provides the auth based on the Cloud IAM principles. As said I don't know the best practices here as I haven't check yet but the links above that Lam shared could be useful too.

Let me know how we could help here, next step seems to me understanding the problem in detail and maybe asking it to google support for an approach.

Regards, Ahmet.

**Comment by Fifciu** [comment]
I think the most helpful would be the mechanism inside the core of commercetools. It would refresh tokens before requests. I see there is a dedicated approach for AzureFunctions and AWSLambda (https://docs.commercetools.com/tutorials/extensions#setting-up-an-api-extension). Let's add something like that for Google Fn. I know it is not a place for commercetools feature requests. But maybe you could forward it from there.

For now, we've decided to use AWSLambda for this particular task as the Extension configuration allows us to provide accessKey and Secret. And for Adyen -> notification module communication, we can write a simple custom Auth Handler in Node.js for AWSLambda.

**Comment by butenkor** [comment]
Hi @Fifciu Is this issue still a topic or can be closed?

**Comment by Fifciu** [comment]
> I think the most helpful would be the mechanism inside the core of commercetools. It would refresh tokens before requests. I see there is a dedicated approach for AzureFunctions and AWSLambda (https://docs.commercetools.com/tutorials/extensions#setting-up-an-api-extension). Let's add something like that for Google Fn. I know it is not a place for commercetools feature requests. But maybe you could forward it from there.
> 
> For now, we've decided to use AWSLambda for this particular task as the Extension configuration allows us to provide accessKey and Secret. And for Adyen -> notification module communication, we can write a simple custom Auth Handler in Node.js for AWSLambda.

I see that the requested functionality is still not available.

**Comment by butenkor** [comment]
> I think the most helpful would be the mechanism inside the core of commercetools. It would refresh tokens before requests. I see there is a dedicated approach for AzureFunctions and AWSLambda

Dedicated approaches exist only because those security features are natively supported by the given cloud providers. It is not the case for GCP functions. One could try to use for example [GCP API Gateway](https://cloud.google.com/api-gateway/docs/secure-traffic-console) and include the API key in the POST google function URL as described [here](https://cloud.google.com/api-gateway/docs/secure-traffic-console#testing_your_api_key). The generated API key according to the [documentation](https://cloud.google.com/endpoints/docs/openapi/when-why-api-key#security_of_api_keys) does not expire unless manually revoked.

>  I know it is not a place for commercetools feature requests. But maybe you could forward it from there.

As you said the right place would be to ask for this feature commercetools through the official [support](https://support.commercetools.com/).
