### ISSUE TITLE
Remove Saved Cards

### ISSUE THREAD

**Issue by milindsingh** [commercetools/commercetools-adyen-integration#949]
The extension allows to allow user to store cards details but I didn't find any way to disable/delete a saved card.

Refer: https://docs.adyen.com/api-explorer/#/Recurring/latest/disable

**Comment by butenkor** [comment]
Hi @milindsingh, storing credit card is part of the Adyen [make payment](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments) request which is an intention to pay and thus is easily supported by the integration since this request is required anyway. Disabling stored credit card is not an intention to pay and thus it does not really require a commercetools payment resource which in turn is required for the integration to work. Adyen has many optional back-office operations which are not required for the actual payment and in such cases a direct communication with Adyen API might be more beneficial instead of using the integration just as a proxy.

**Comment by milindsingh** [comment]
Thanks @butenkor 

I was just curious to know if it was possible to do this in Extension, as integration the Adyen APIs at 2 places (Merchant Server and Adyen Extension) is something I was trying to avoid.

**Comment by butenkor** [comment]
> I was just curious to know if it was possible to do this in Extension

In general almost anything is possible but the question is if it is reasonable and at which costs. The idea of the integration is to shorten the integration time of the users, simplify the checkout process and providing a value by applying best practices in regards to handling the payment, its state, Adyen payment notification mappings and similar. Adding support for all the possible Adyen non payment related operations would undermine the given ideas as it would mean adding more complexity and using the integration just as a proxy without added benefits.

> integration the Adyen APIs at 2 places (Merchant Server and Adyen Extension) is something I was trying to avoid

Fair point but on the other hand this operation has nothing to do with commercetools and handling this directly with Adyen seems straight forward/simple.

**Comment by butenkor** [comment]
Hi @milindsingh . Sorry for the late reply but the feature is implemented and released some time ago: https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.11.0
